### ISSUE TITLE
Add the new KUTTL to KUDO

### ISSUE THREAD

**Issue by kensipe** [kudobuilder/kuttl#11]
KUDO needs to use this new dependency

+ needs to be added for `kudo test`
+ inject kudo manager into the tests (with designed approach)

**Comment by gerred** [comment]
I think early on we could skip the second bullet point. While it would be nice to have a data model for setup and teardown, side effects are something that right now can be solved by a makefile in downstream projects. It's not optimal, but it does get us along the way of having kuttl be a sharp, precise tool in it's existing form, if not a bit reductionist.

@jbarrick-mesosphere what do you think? I'm thinking we yank any specific controller functionality directly, maintain kudo test as it is, and then make the highest priority for kuttl to fix this issue so that KUDO can migrate.
