### ISSUE TITLE
First Test Case following document always got successful

### ISSUE THREAD

**Issue by smarkm** [kudobuilder/kuttl#165]
Hi, I am trying to use `kuttl` , I'm following the document test case https://kuttl.dev/docs/kuttl-test-harness.html#writing-your-first-test on my local cluster and with the command `kubectl kuttl test ${casedir}`, but I got always successful even though I changed the `00-assert.yaml` , so what am I missing?
the screenshot will like this:
![image](https://user-images.githubusercontent.com/5517120/87331297-53b91600-c56c-11ea-9a58-738d64ae9cbe.png)

**Environment**:
- Kubernetes version (v1.17.2):
- KUTTL version (0.5.1):
- OS (ubuntu 18.04):
- Kernel (5.3.0-40-generic):

**Comment by kensipe** [comment]
@smarkm the issue here is the test is never run.   The testsuite directory is `mtest` and `case1` is a test folder.  you can't point kuttl at a test folder... it must be pointed to a testsuite.  This would run correctly (crosses fingers)... if you `kubectl kuttl test mtest`.   if you have more than 1 test and only want to run 1.. you can `kubectl kuttl test mtest --test case1`
